
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    ip-address: 43.201.192.159
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://13.124.197.227:8761/eureka

server:
  port: 8080